### ISSUE TITLE
The import_blogs command creates duplicated images

### ISSUE THREAD

**Issue by m1kola** [cca/libraries_wagtail#39]
If there are pages in a CSV file that use the same image, the `import_blogs` command will download and create duplicates, because `import_blogs` command doesn't check if the image is already exist in the local media dir/DB.

Not sure if this issue is important. Probably it will produce only few duplicates, but worth checking.

**Comment by phette23** [comment]
Hmm I guess I could fix this by first searching for an image with a matching name in `add_img_to_wagtail` and then, if one is found, returning that instead of downloading a new one?

**Comment by m1kola** [comment]
> Hmm I guess I could fix this by first searching for an image with a matching name in add_img_to_wagtail and then, if one is found, returning that instead of downloading a new one?

Yes, but search by filename is not reliable, I think. It's possible to have 2 or more images with the same name in Wagtail.

If we need to perform import only once, we can store a list of image URLs in memory and check them during import process.

If we need to perform periodic imports, we need to store the list of URLs in DB, I think.

**Comment by phette23** [comment]
The import only needs to run once. The idea is to carry over the content from our old blog to the new site.

**Comment by m1kola** [comment]
@phette23 great! This means we can just temporary save the list of URLs in memory during import process. It should be easier. The only thing that we should take into account: we need transaction here: we must rollback all changes if the `import_blogs ` command fails in the middle of the import process.

**Comment by phette23** [comment]
We've already launched the live site and I don't anticipate running this command ever again. I'll put a comment on it in case it does come up again, but it doesn't make sense to me to commit time to working on this.
