### ISSUE TITLE
announcement / alert banner for the website

### ISSUE THREAD

**Issue by phette23** [cca/libraries_wagtail#49]
Probably display just below the header somewhere, allow us to make announcements like "X system is out" etc.

Django has a "messages" feature which should be good for this: https://docs.djangoproject.com/en/1.11/ref/contrib/messages/

**Comment by phette23** [comment]
See https://cca.edu feature that we should build off of. Here's the code on GitLab (CCA sign-in required): https://gitlab.com/california-college-of-the-arts/cca-edu/tree/althea/alert-banner-qa-response/cca/alerts

The new feature was up on the cca.edu staging server for a bit but I don't know if that's still true.

**Comment by phette23** [comment]
This branch on Portal may actually be the most useful since the global CCA alerts will originate on CCA.edu but Portal/Libraries will need to consume them - https://github.com/cca/portal/commits/althea/merge-faq-and-alert

**Comment by inostia** [comment]
Hi @phette23 I got an email notification for this. Actually the alerts originate on Portal and propagate to cca.edu, so if you wanted to receive Portal alerts you could replicate the code on cca.edu and we'll just add your API endpoint to the settings on Portal.

**Comment by phette23** [comment]
Ah OK thanks for clarifying, I will look at cca.edu then.

**Comment by phette23** [comment]
<img width="738" alt="Screen Shot 2019-10-31 at 12 35 45" src="https://user-images.githubusercontent.com/1024833/67980133-fb5b0780-fbda-11e9-9e9b-e5ddd50276b7.png">

Not bad for a few hours work. Obviously I don't have the API part working, and banner needs to be adjusted up just a tiny bit, but hey we have working alerts.

**Comment by inostia** [comment]
Nice. To lock down the API on cca.edu I decided to use a [DRF library](https://github.com/davesque/django-rest-framework-simplejwt) that allows a user to request an authentication token, which can then be used to `POST` alerts to the API. Ideally, we could just need a user/password combination for a valid libraries.cca.edu user, add your `/token/` endpoint, and `POST`/`DELETE` to your REST endpoints whenever we publish/unpublish alerts.

I wish we could package it up into a library so we don't have dupe code on cca.edu and libraries.cca.edu, I'll think about it.

**Comment by phette23** [comment]
@inostia yeah I saw that. You have to add an extra library to get the token authentication? I'm just surprised that doesn't come baked into DRF/Wagtail API.

I installed that, copied the few lines from cca/api/urls.py into our urls.py, and wholesale copied the cca/alerts/api directory. I successfully tested getting and verifying a token just using the DRF browser interface. I have accounts for you, Althea, Analisa, & Nick in libraries.cca.edu already so you should be able to use any of those. I don't see anything at the /api/v1/alerts/ endpoint when I navigate there, though. I tried creating an alert using a token & the code in `[push_alert_to_cca_edu](https://github.com/cca/portal/blob/8cbfb6ea643662b7a317585a778e8df3cb27d518/portal/apps/cms/signal_hooks.py#L32)` & it returned a 403 CSRF error at first & then, after I disabled CSRF middleware just to test, a 404. It seems like I set up the alerts router wrong somehow?

**Comment by phette23** [comment]
Fixed header height issue. Style looks fine now.

<img width="387" alt="Screen Shot 2019-10-31 at 13 08 23" src="https://user-images.githubusercontent.com/1024833/67985034-35310b80-fbe5-11e9-9c9c-8f9cc095ddfd.png">

<img width="1440" alt="Screen Shot 2019-10-31 at 13 08 26" src="https://user-images.githubusercontent.com/1024833/67985039-382bfc00-fbe5-11e9-8577-0cb97ce3eff2.png">

**Comment by phette23** [comment]
All this work is happening on https://github.com/cca/libraries_wagtail/tree/iss49 btw

**Comment by phette23** [comment]
Never mind! I figured it out. I couldn't get it to work the way I wanted it to, with most of the URLs code in the main urls.py file, so I split out the URLs file underneath the alerts app like cca.edu does and it worked immediately. I can `POST` to successfully create an alert and it overwrites any existing alerts.
